//! Authoritative bytes for SPEC-SERVER §§6–7 and §15.
//! Read-only by default; `UPDATE_GOLDEN=1` deliberately rebuilds signatures
//! and the complete manifest from the checked-in request bodies and fields.
#![allow(clippy::unwrap_used)] // Test failures are assertions.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use ed25519_dalek::{Signature, Signer, SigningKey};
use mkit_core::hash::{from_hex, hash, to_hex, to_hex_bytes};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct SignatureFile {
    vectors: Vec<SignatureVector>,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct SignatureVector {
    test_key_label: String,
    test_seed_hex: String,
    key_id: String,
    audience: String,
    procedure: String,
    created_at_ms: String,
    expires_at_ms: String,
    nonce: String,
    body_file: String,
    body_utf8: String,
    body_digest: String,
    canonical: String,
    canonical_blake3: String,
    public_key: String,
    signature: String,
    headers: BTreeMap<String, String>,
}

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden/server-hooks")
}

fn rebuild(vector: &SignatureVector, dir: &Path) -> SignatureVector {
    let mut expected = vector.clone();
    let body = fs::read(dir.join(&vector.body_file)).unwrap();
    expected.body_utf8 = String::from_utf8(body.clone()).unwrap();
    expected.body_digest = format!("body:{}", to_hex(&hash(&body)));
    expected.canonical = [
        "mkit-hook:v1",
        &vector.key_id,
        &vector.audience,
        &vector.procedure,
        &expected.body_digest,
        &vector.created_at_ms,
        &vector.expires_at_ms,
        &vector.nonce,
    ]
    .join("\n");
    let digest = hash(expected.canonical.as_bytes());
    expected.canonical_blake3 = to_hex(&digest);
    let key = SigningKey::from_bytes(&from_hex(&vector.test_seed_hex).unwrap());
    expected.public_key = to_hex_bytes(key.verifying_key().as_bytes());
    expected.signature = to_hex_bytes(&key.sign(&digest).to_bytes());
    expected.headers = BTreeMap::from([
        ("X-Mkit-Hook-Version".into(), "1".into()),
        ("X-Mkit-Hook-Key-Id".into(), vector.key_id.clone()),
        ("X-Mkit-Hook-Audience".into(), vector.audience.clone()),
        (
            "X-Mkit-Hook-Created-At".into(),
            vector.created_at_ms.clone(),
        ),
        (
            "X-Mkit-Hook-Expires-At".into(),
            vector.expires_at_ms.clone(),
        ),
        ("X-Mkit-Hook-Nonce".into(), vector.nonce.clone()),
        ("X-Mkit-Hook-Digest".into(), expected.body_digest.clone()),
        ("X-Mkit-Hook-Signature".into(), expected.signature.clone()),
    ]);
    expected
}

fn fixture_names(dir: &Path) -> BTreeSet<String> {
    fs::read_dir(dir)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().into_string().unwrap())
        .filter(|name| name != "MANIFEST.txt")
        .collect()
}

fn manifest(dir: &Path) -> String {
    let mut result = String::from(
        "# Server-hook golden vectors (SPEC-SERVER v1)\n\
         # TEST KEYS ONLY; generated by golden_server_hooks\n\
         # Format: <name> <blake3-hex-of-file-bytes>\n",
    );
    for name in fixture_names(dir) {
        let digest = to_hex(&hash(&fs::read(dir.join(&name)).unwrap()));
        writeln!(result, "{name} {digest}").unwrap();
    }
    result
}

fn assert_manifest(dir: &Path) {
    let stored = fs::read_to_string(dir.join("MANIFEST.txt")).unwrap();
    let mut covered = BTreeSet::new();
    for line in stored.lines().filter(|line| !line.starts_with('#')) {
        let columns: Vec<_> = line.split_whitespace().collect();
        assert_eq!(columns.len(), 2, "invalid manifest line: {line}");
        let name = columns[0];
        assert!(covered.insert(name.to_owned()), "duplicate fixture: {name}");
        let bytes = fs::read(dir.join(name)).unwrap();
        assert_eq!(columns[1], to_hex(&hash(&bytes)), "fixture: {name}");
    }
    assert_eq!(
        covered,
        fixture_names(dir),
        "manifest must cover every file"
    );
}

fn assert_signature(vector: &SignatureVector, dir: &Path) {
    assert!(vector.test_key_label.starts_with("TEST KEY ONLY:"));
    assert_eq!(
        vector,
        &rebuild(vector, dir),
        "vector: {}",
        vector.procedure
    );
    assert_eq!(vector.canonical.lines().count(), 8);
    assert!(!vector.canonical.ends_with('\n'));
    let created = vector.created_at_ms.parse::<i64>().unwrap();
    let expires = vector.expires_at_ms.parse::<i64>().unwrap();
    assert!((1..=300_000).contains(&(expires - created)));
    assert_eq!(created.to_string(), vector.created_at_ms);
    assert_eq!(expires.to_string(), vector.expires_at_ms);
    assert_eq!(vector.nonce.len(), 64);
    assert!(
        vector
            .nonce
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
    );

    let key = SigningKey::from_bytes(&from_hex(&vector.test_seed_hex).unwrap());
    let mut signature_bytes = [0_u8; 64];
    assert_eq!(vector.signature.len(), 128);
    signature_bytes[..32].copy_from_slice(&from_hex(&vector.signature[..64]).unwrap());
    signature_bytes[32..].copy_from_slice(&from_hex(&vector.signature[64..]).unwrap());
    let signature = Signature::from_bytes(&signature_bytes);
    let digest = hash(vector.canonical.as_bytes());
    key.verifying_key()
        .verify_strict(&digest, &signature)
        .unwrap();
    let mut tampered = digest;
    tampered[0] ^= 1;
    assert!(
        key.verifying_key()
            .verify_strict(&tampered, &signature)
            .is_err()
    );
    let body = fs::read(dir.join(&vector.body_file)).unwrap();
    assert_eq!(vector.body_utf8.as_bytes(), body);
    assert_eq!(
        vector.headers["X-Mkit-Hook-Digest"],
        format!("body:{}", to_hex(&hash(&body)))
    );
}

#[test]
fn golden_server_hooks() {
    let dir = golden_dir();
    let path = dir.join("signature.json");
    let mut file: SignatureFile = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    assert_eq!(file.vectors.len(), 2);
    assert_eq!(
        file.vectors[0].procedure,
        "/mkit.server.hooks.v1.HooksService/Admit"
    );
    assert_eq!(
        file.vectors[1].procedure,
        "/mkit.server.hooks.v1.HooksService/Outcome"
    );
    if std::env::var("UPDATE_GOLDEN").as_deref() == Ok("1") {
        file.vectors = file.vectors.iter().map(|v| rebuild(v, &dir)).collect();
        fs::write(
            &path,
            format!("{}\n", serde_json::to_string_pretty(&file).unwrap()),
        )
        .unwrap();
        fs::write(dir.join("MANIFEST.txt"), manifest(&dir)).unwrap();
    }
    assert_manifest(&dir);
    for vector in &file.vectors {
        assert_signature(vector, &dir);
    }
    let keys: serde_json::Value =
        serde_json::from_slice(&fs::read(dir.join("key-list.json")).unwrap()).unwrap();
    assert_eq!(keys["version"], 1);
    assert_eq!(keys["keys"][0]["alg"], "ed25519");
    assert_eq!(keys["keys"][0]["keyId"], file.vectors[0].key_id);
    assert_eq!(keys["keys"][0]["publicKey"], file.vectors[0].public_key);
}
