#!/usr/bin/env node
// Generate public/_headers (Cloudflare's static-asset headers mechanism) from the
// single source of truth in src/security-policy.js.
//
// Why this exists: the Worker middleware (src/security-headers.ts) only runs for
// routes the Worker handles — `/` and the installer short-circuit. Every prerendered
// page (/tree, /hash, …) is served straight from the Cloudflare Assets binding and
// never reaches the Worker, so without `_headers` those routes ship with NO security
// headers. `_headers` applies the policy to `/*` (all routes), and generating it from
// the shared module guarantees it can't drift from the Worker path.
//
// Run BEFORE `waku build` (which collects public/ into dist/public) so the generated
// file ships. The policy module is plain `.js` so this imports cleanly on any Node
// (the Cloudflare Workers Builds image's `node` may not strip types from `.ts`).
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SECURITY_HEADERS } from '../src/security-policy.js'

const here = dirname(fileURLToPath(import.meta.url))
const headersPath = resolve(here, '..', 'public', '_headers')

// Kept as the single source of truth for both the extensions and the routes below —
// assert-headers.mjs loops over the identical lists to verify each rule survived.
const IMMUTABLE_IMAGE_EXTS = ['svg', 'png', 'ico', 'webp']
const SHORT_TTL_ROUTES = ['/concepts', '/multiplayer', '/parity', '/performance', '/specs', '/RSC/*']

const body = SECURITY_HEADERS.map(([name, value]) => `  ${name}: ${value}`).join('\n')
const immutableImageRules = IMMUTABLE_IMAGE_EXTS.map(
  (ext) => `/*.${ext}\n  Cache-Control: public, max-age=31536000, immutable`,
).join('\n')
const shortTtlRules = SHORT_TTL_ROUTES.map(
  (route) => `${route}\n  Cache-Control: public, max-age=300, stale-while-revalidate=86400`,
).join('\n')
const contents = `# GENERATED by scripts/gen-headers.mjs from src/security-policy.js — DO NOT EDIT BY HAND.
# Cloudflare static-asset headers: applied to every route served by the Assets binding,
# including the prerendered demo pages that bypass the Worker. Edit the policy in
# src/security-policy.js and re-run \`node scripts/gen-headers.mjs\` (wired into the build).
/*
${body}

# Cloudflare's default for the Assets binding is \`Cache-Control: public, max-age=0,
# must-revalidate\` for every file, hashed or not — every visit pays a revalidation
# round trip even for /assets/* files, which are content-hashed by the build (a
# content change always ships a new filename) and are therefore genuinely immutable.
# This rule opts them into long-lived caching; it's declared after \`/*\` so it wins
# over that block for any header both set (none currently overlap).
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# Image files served at a fixed, non-hashed public/ path (grid-fallback.svg today). These
# aren't content-hashed, so a real content change at the same URL won't bust the cache
# until max-age expires — the same tradeoff officialunofficial.com's _headers makes for its
# own favicon/logo. Acceptable for images this static; rename the file to force a refresh.
# Deliberately does NOT cover install.sh/install.ps1/SKILL.md/robots.txt — those can change
# between releases and immutable caching would be actively wrong for them.
${immutableImageRules}

# The prerendered demo pages and their RSC payloads are also Assets-binding-served — same
# must-revalidate-on-every-visit default as above, but these are real HTML/RSC responses
# whose content CAN change at the same path on a redeploy, so they get a short max-age
# (not immutable) plus stale-while-revalidate so a redeploy's staleness window is bounded
# rather than serving the old page forever until explicitly revalidated. \`/\` is excluded:
# it's the sole run_worker_first route (see src/cache-headers.ts), so the Assets binding
# never serves it and a rule here would be dead code.
${shortTtlRules}
`

const previous = (() => {
  try {
    return readFileSync(headersPath, 'utf8')
  } catch {
    return null
  }
})()

if (previous === contents) {
  console.log(`gen-headers: ok (public/_headers already up-to-date, ${SECURITY_HEADERS.length} headers)`)
} else {
  writeFileSync(headersPath, contents)
  console.log(`gen-headers: wrote public/_headers (${SECURITY_HEADERS.length} headers)`)
}
