#!/usr/bin/env node
// Generate public/_headers (Cloudflare's static-asset headers mechanism) from the
// single source of truth in src/security-policy.js.
//
// Why this exists: the Worker middleware (src/security-headers.ts) only runs for
// routes the Worker handles — `/` and the installer short-circuit. Every prerendered
// page (/tree, /hash, …) is served straight from the Cloudflare Assets binding and
// never reaches the Worker, so without `_headers` those routes ship with NO security
// headers. `_headers` applies the policy to `/*` (all routes), and generating it from
// the shared module guarantees it can't drift from the Worker path.
//
// Run BEFORE `waku build` (which collects public/ into dist/public) so the generated
// file ships. The policy module is plain `.js` so this imports cleanly on any Node
// (the Cloudflare Workers Builds image's `node` may not strip types from `.ts`).
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SECURITY_HEADERS } from '../src/security-policy.js'

const here = dirname(fileURLToPath(import.meta.url))
const headersPath = resolve(here, '..', 'public', '_headers')

const body = SECURITY_HEADERS.map(([name, value]) => `  ${name}: ${value}`).join('\n')
const contents = `# GENERATED by scripts/gen-headers.mjs from src/security-policy.js — DO NOT EDIT BY HAND.
# Cloudflare static-asset headers: applied to every route served by the Assets binding,
# including the prerendered demo pages that bypass the Worker. Edit the policy in
# src/security-policy.js and re-run \`node scripts/gen-headers.mjs\` (wired into the build).
/*
${body}

# Cloudflare's default for the Assets binding is \`Cache-Control: public, max-age=0,
# must-revalidate\` for every file, hashed or not — every visit pays a revalidation
# round trip even for /assets/* files, which are content-hashed by the build (a
# content change always ships a new filename) and are therefore genuinely immutable.
# This rule opts them into long-lived caching; it's declared after \`/*\` so it wins
# over that block for any header both set (none currently overlap).
/assets/*
  Cache-Control: public, max-age=31536000, immutable
`

const previous = (() => {
  try {
    return readFileSync(headersPath, 'utf8')
  } catch {
    return null
  }
})()

if (previous === contents) {
  console.log(`gen-headers: ok (public/_headers already up-to-date, ${SECURITY_HEADERS.length} headers)`)
} else {
  writeFileSync(headersPath, contents)
  console.log(`gen-headers: wrote public/_headers (${SECURITY_HEADERS.length} headers)`)
}
