#!/usr/bin/env node
// Post-build guard: fail the build if the security `_headers` file did not ship into
// dist/public, or if it is missing an expected directive. `_headers` is the ONLY thing
// applying security headers to the prerendered demo pages (/tree, /hash, …) — they are
// served by the Cloudflare Assets binding and bypass the Worker middleware — so a missing
// or stale file silently ships those pages with no CSP/HSTS/etc. The file is generated by
// scripts/gen-headers.mjs from src/security-policy.js and staged by `waku build`. Run after
// `waku build`.
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SECURITY_HEADERS } from '../src/security-policy.js'

const here = dirname(fileURLToPath(import.meta.url))
const headersPath = resolve(here, '..', 'dist', 'public', '_headers')

if (!existsSync(headersPath)) {
  console.error(
    `assert-headers: missing ${headersPath} — did scripts/gen-headers.mjs run before \`waku build\`? Without it, asset-served pages ship no security headers.`,
  )
  process.exit(1)
}

const contents = readFileSync(headersPath, 'utf8')
const failures = []

// Must apply to all routes.
if (!/^\/\*\s*$/m.test(contents)) {
  failures.push('no `/*` (catch-all) rule found')
}

// Every header name from the shared policy must be present with its value.
for (const [name, value] of SECURITY_HEADERS) {
  if (!contents.includes(`${name}: ${value}`)) {
    failures.push(`missing or mismatched header: ${name}`)
  }
}

// Spot-check the directives most likely to break the live demos if dropped, so a
// future policy edit that strips them fails loudly here rather than in production.
for (const directive of ['wasm-unsafe-eval', 'frame-ancestors', 'Strict-Transport-Security']) {
  if (!contents.includes(directive)) {
    failures.push(`expected directive/header not present: ${directive}`)
  }
}

if (failures.length) {
  console.error('assert-headers: dist/public/_headers is broken —')
  for (const f of failures) console.error(`  - ${f}`)
  process.exit(1)
}
console.log(`assert-headers: ok (dist/public/_headers shipped with ${SECURITY_HEADERS.length} headers on /*)`)
