#!/usr/bin/env node
// Generate public/_headers (Cloudflare's static-asset headers mechanism) from the
// single source of truth in src/security-policy.ts.
//
// Why this exists: the Worker middleware (src/security-headers.ts) only runs for
// routes the Worker handles — `/` and the installer short-circuit. Every prerendered
// page (/tree, /hash, …) is served straight from the Cloudflare Assets binding and
// never reaches the Worker, so without `_headers` those routes ship with NO security
// headers. `_headers` applies the policy to `/*` (all routes), and generating it from
// the shared module guarantees it can't drift from the Worker path.
//
// Run BEFORE `waku build` (which collects public/ into dist/public) so the generated
// file ships. Node ≥23 strips types from the imported .ts module natively.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SECURITY_HEADERS } from '../src/security-policy.ts'

const here = dirname(fileURLToPath(import.meta.url))
const headersPath = resolve(here, '..', 'public', '_headers')

const body = SECURITY_HEADERS.map(([name, value]) => `  ${name}: ${value}`).join('\n')
const contents = `# GENERATED by scripts/gen-headers.mjs from src/security-policy.ts — DO NOT EDIT BY HAND.
# Cloudflare static-asset headers: applied to every route served by the Assets binding,
# including the prerendered demo pages that bypass the Worker. Edit the policy in
# src/security-policy.ts and re-run \`node scripts/gen-headers.mjs\` (wired into the build).
/*
${body}
`

const previous = (() => {
  try {
    return readFileSync(headersPath, 'utf8')
  } catch {
    return null
  }
})()

if (previous === contents) {
  console.log(`gen-headers: ok (public/_headers already up-to-date, ${SECURITY_HEADERS.length} headers)`)
} else {
  writeFileSync(headersPath, contents)
  console.log(`gen-headers: wrote public/_headers (${SECURITY_HEADERS.length} headers)`)
}
