//! Model-based conformance tests for mkit's formal models (Linear MKIT-22).
//!
//! This library is intentionally empty. The tests live in `tests/`:
//!
//! - `formal_refs_conformance.rs` replays the ITF traces of
//!   `formal/quint/refs/refs_mbt.qnt` (checked in under
//!   `tests/fixtures/formal_refs/`, regenerated by
//!   `formal/scripts/gen-refs-traces.sh`) against `mkit_core::refs`,
//!   `mkit_core::ops::recovery`, `FileTransport` and `MemoryTransport`.
