//! Shared native/wasm regression for corrupt zstd working memory (R-203).

use std::alloc::{GlobalAlloc, Layout, System};
use std::sync::atomic::{AtomicUsize, Ordering};

use mkit_core::pack::{DecodeLimits, NoExternalBases, PackError, decode_frame_with};
use mkit_core::{Blob, Object, hash, serialize};

struct CountingAllocator;
static LIVE: AtomicUsize = AtomicUsize::new(0);
static PEAK: AtomicUsize = AtomicUsize::new(0);

#[global_allocator]
static ALLOCATOR: CountingAllocator = CountingAllocator;

fn account(size: usize) {
    let live = LIVE.fetch_add(size, Ordering::SeqCst) + size;
    PEAK.fetch_max(live, Ordering::SeqCst);
}

// SAFETY: every allocation and deallocation uses the original System layout;
// the atomics only observe requested live bytes and do not alter pointers.
unsafe impl GlobalAlloc for CountingAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let pointer = unsafe { System.alloc(layout) };
        if !pointer.is_null() {
            account(layout.size());
        }
        pointer
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        let pointer = unsafe { System.alloc_zeroed(layout) };
        if !pointer.is_null() {
            account(layout.size());
        }
        pointer
    }

    unsafe fn dealloc(&self, pointer: *mut u8, layout: Layout) {
        LIVE.fetch_sub(layout.size(), Ordering::SeqCst);
        unsafe { System.dealloc(pointer, layout) };
    }
}

// A fixed 8 MiB window can grow an 8 MiB ring to 16 MiB before freeing the
// old ring: 24 MiB transiently. The other 4 MiB covers decoder tables and block
// buffers, independently of attacker output length. This meters requested live
// bytes, not allocator metadata or whole-process resident memory.
const WORKING_ALLOWANCE: usize = 28 << 20;
const SMALL_CAP: usize = 64 << 10;
const BLOCK_MAXIMUM: usize = 128 << 10;

fn block(frame: &mut Vec<u8>, kind: u32, size: usize, last: bool, bytes: &[u8]) {
    let header = (u32::try_from(size).unwrap() << 3) | (kind << 1) | u32::from(last);
    frame.extend_from_slice(&header.to_le_bytes()[..3]);
    frame.extend_from_slice(bytes);
}

fn pack_frame(zstd: &[u8], claim: usize) -> Vec<u8> {
    let mut frame = vec![0x03];
    frame.extend_from_slice(&u32::try_from(zstd.len() + 4).unwrap().to_le_bytes());
    frame.extend_from_slice(&u32::try_from(claim).unwrap().to_le_bytes());
    frame.extend_from_slice(zstd);
    frame
}

fn windowed_frame(window_descriptor: u8) -> Vec<u8> {
    vec![0x28, 0xb5, 0x2f, 0xfd, 0, window_descriptor]
}

/// Exact bytes generated by the reviewer's corrupt-zstd.rs for n=2000:
/// a 4,524-byte frame previously expanded ~201 MiB before its first read.
fn sequence_flood(n: usize) -> Vec<u8> {
    let mut frame = windowed_frame(0x68);
    block(&mut frame, 0, 4, false, b"AAAA");
    let [high, low] = u16::try_from(n).unwrap().to_be_bytes();
    let mut body = vec![0, 0x80 + high, low, 0x54, 0, 2, 52];
    body.resize(body.len() + n * 18 / 8, 0);
    body.push(1);
    block(&mut frame, 2, body.len(), true, &body);
    frame
}

fn blob(size: usize) -> Vec<u8> {
    serialize::serialize(&Object::Blob(Blob {
        data: vec![b'A'; size],
    }))
    .unwrap()
}

fn reject_with_bounded_heap(name: &str, zstd: &[u8], claim: usize) {
    // Exclude the already acquired frame: this meters allocations during
    // decode, including allocations subsequently freed before rejection.
    let frame = pack_frame(zstd, claim);
    let baseline = LIVE.load(Ordering::SeqCst);
    PEAK.store(baseline, Ordering::SeqCst);
    let result = decode_frame_with(
        &frame,
        2,
        &mut NoExternalBases,
        DecodeLimits::default().with_max_decoded_bytes(claim as u64),
    );
    let peak = PEAK.load(Ordering::SeqCst).saturating_sub(baseline);
    println!(
        "{name}: claim={claim}, peak_decode_alloc_bytes={peak}, result={:?}",
        result.as_ref().map(|(_, bytes)| bytes.len())
    );
    assert!(
        peak <= claim + WORKING_ALLOWANCE,
        "{name}: decoder allocated {peak} bytes above baseline, cap {claim} + {WORKING_ALLOWANCE}"
    );
    assert!(
        matches!(result, Err(PackError::ZstdDecompress(_))),
        "{name}: malformed compression must fail before object validation"
    );
}

pub(crate) fn corrupt_zstd_frames_bound_heap() {
    let reviewer = sequence_flood(2000);
    assert_eq!(reviewer.len(), 4524);
    reject_with_bounded_heap("reviewer sequence flood", &reviewer, SMALL_CAP);
    reject_with_bounded_heap("reviewer at scheduled 1 MiB cap", &reviewer, 1 << 20);
    reject_with_bounded_heap("larger sequence flood", &sequence_flood(4096), SMALL_CAP);

    let mut rle = windowed_frame(0x68);
    block(&mut rle, 1, BLOCK_MAXIMUM + 1, true, b"A");
    reject_with_bounded_heap("RLE block over 128 KiB", &rle, BLOCK_MAXIMUM + 1);

    // Canonical objects ensure acceptance cannot hide behind InvalidObject.
    let raw_object = blob(BLOCK_MAXIMUM);
    let mut raw = windowed_frame(0x68);
    block(&mut raw, 0, raw_object.len(), true, &raw_object);
    reject_with_bounded_heap("raw block over 128 KiB", &raw, raw_object.len());

    let mut huge_window = windowed_frame(0x70); // 16 MiB; allowed claim is larger.
    block(&mut huge_window, 0, 0, true, &[]);
    reject_with_bounded_heap("16 MiB window", &huge_window, 16 << 20);

    // Non-single-segment FCS=256, 8 MiB window, actual canonical object >256.
    let lying_object = blob(512);
    let mut lying_size = vec![0x28, 0xb5, 0x2f, 0xfd, 0x40, 0x68, 0, 0];
    block(&mut lying_size, 0, lying_object.len(), true, &lying_object);
    reject_with_bounded_heap("lying content size", &lying_size, lying_object.len());

    let object = blob(1500);
    let mut undersized_window = windowed_frame(0); // 1 KiB window.
    block(&mut undersized_window, 0, object.len(), true, &object);
    reject_with_bounded_heap(
        "raw block over 1 KiB window",
        &undersized_window,
        object.len(),
    );

    // Legal regenerated size, but the compressed body itself exceeds the
    // 1 KiB window by its literals/sequence headers (RFC 8878 §3.1.1.2.4).
    let mut compressed_body = ((1024u16 << 4) | 4).to_le_bytes().to_vec();
    compressed_body.extend_from_slice(&object[..1024]);
    compressed_body.push(0); // zero sequences
    let mut compressed = windowed_frame(0);
    block(
        &mut compressed,
        2,
        compressed_body.len(),
        false,
        &compressed_body,
    );
    block(
        &mut compressed,
        0,
        object.len() - 1024,
        true,
        &object[1024..],
    );
    reject_with_bounded_heap(
        "compressed body over 1 KiB window",
        &compressed,
        object.len(),
    );

    let mut tiny_rle_window = windowed_frame(0);
    block(&mut tiny_rle_window, 1, 1025, true, b"A");
    reject_with_bounded_heap("RLE block over 1 KiB window", &tiny_rle_window, 1025);

    // RFC block maximum applies per block: a valid multi-block frame may
    // decode more than its tiny window in total, and the exact limit is valid.
    let mut valid = windowed_frame(0);
    block(&mut valid, 0, 1024, false, &object[..1024]);
    block(&mut valid, 0, object.len() - 1024, true, &object[1024..]);
    let decoded = decode_frame_with(
        &pack_frame(&valid, object.len()),
        2,
        &mut NoExternalBases,
        DecodeLimits::default().with_max_decoded_bytes(object.len() as u64),
    )
    .unwrap();
    assert_eq!(decoded, (hash::hash(&object), object));

    // Exercise the largest admitted window's ring growth, including live
    // old/new allocation overlap, with valid per-block raw output >8 MiB.
    let long_object = blob(9 << 20);
    let mut long = windowed_frame(0x68);
    let chunks = long_object.chunks(BLOCK_MAXIMUM);
    let count = chunks.len();
    for (index, chunk) in chunks.enumerate() {
        block(&mut long, 0, chunk.len(), index + 1 == count, chunk);
    }
    let frame = pack_frame(&long, long_object.len());
    let baseline = LIVE.load(Ordering::SeqCst);
    PEAK.store(baseline, Ordering::SeqCst);
    let decoded = decode_frame_with(
        &frame,
        2,
        &mut NoExternalBases,
        DecodeLimits::default().with_max_decoded_bytes(long_object.len() as u64),
    )
    .unwrap();
    let peak = PEAK.load(Ordering::SeqCst).saturating_sub(baseline);
    println!(
        "valid 8 MiB window: claim={}, peak_decode_alloc_bytes={peak}",
        long_object.len()
    );
    assert!(peak <= long_object.len() + WORKING_ALLOWANCE);
    assert_eq!(decoded, (hash::hash(&long_object), long_object));
}
