//! Immutable v0.5.0 encoder output; fixtures are never regenerated by tests.
#![allow(clippy::unwrap_used)]

pub(crate) fn json<T: serde::Serialize + serde::de::DeserializeOwned>(
    name: &str,
    bytes: &[u8],
) -> T {
    let row: T = serde_json::from_slice(bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
    assert_eq!(serde_json::to_vec(&row).unwrap(), bytes, "{name}");
    row
}

pub(crate) fn value(body: &[u8], prefix: &[u8]) -> mkit_server::Value {
    mkit_server::Value::new([prefix, body].concat())
}

pub(crate) fn hex(bytes: &str) -> mkit_server::Value {
    let bytes = bytes.trim();
    assert!(bytes.len().is_multiple_of(2));
    mkit_server::Value::new(
        (0..bytes.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&bytes[i..i + 2], 16).unwrap())
            .collect::<Vec<_>>(),
    )
}
macro_rules! hex_fixture {
    ($name:literal) => {
        crate::stored_golden::hex(include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/stored-v0.5.0/",
            $name,
            ".hex"
        )))
    };
}
pub(crate) use hex_fixture;

macro_rules! json_fixture {
    ($ty:ty, $name:literal) => {
        crate::stored_golden::json::<$ty>(
            $name,
            include_bytes!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/tests/fixtures/stored-v0.5.0/",
                $name,
                ".json"
            )),
        )
    };
}
pub(crate) use json_fixture;
macro_rules! row_fixture {
    ($name:literal, $prefix:expr) => {
        crate::stored_golden::value(
            include_bytes!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/tests/fixtures/stored-v0.5.0/",
                $name,
                ".json"
            )),
            $prefix,
        )
    };
}
pub(crate) use row_fixture;
