#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Validates a CycloneDX SBOM file against the CycloneDX JSON schema via
# `cyclonedx-cli validate`, plus a couple of mkit-specific sanity checks
# (non-empty component list, our own package present) that a schema-valid
# but empty/wrong SBOM would still pass.
#
# WHY: release.yml's SBOM (`sbom.cdx.json`, generated by anchore/sbom-action)
# is shipped as a real release artifact and is part of the SHA256SUMS chain
# users are told to trust — a schema violation or an empty component list
# would ship silently otherwise, since nothing previously checked the SBOM's
# own structure.
#
# Usage: scripts/validate-sbom.sh <path/to/sbom.cdx.json>

set -euo pipefail

sbom="${1:-}"
if [ -z "$sbom" ]; then
  echo "usage: $0 <path/to/sbom.cdx.json>" >&2
  exit 2
fi
if [ ! -f "$sbom" ]; then
  echo "validate-sbom: file not found: $sbom" >&2
  exit 1
fi

if ! command -v cyclonedx >/dev/null 2>&1; then
  echo "validate-sbom: cyclonedx-cli not installed — install: https://github.com/CycloneDX/cyclonedx-cli" >&2
  exit 1
fi

echo "validate-sbom: schema-validating ${sbom}"
cyclonedx validate --input-file "$sbom" --input-format json --fail-on-errors

component_count=$(python3 -c "
import json, sys
with open('${sbom}') as f:
    bom = json.load(f)
print(len(bom.get('components', [])))
")
echo "validate-sbom: ${component_count} component(s) listed"
if [ "$component_count" -lt 1 ]; then
  echo "validate-sbom: ERROR: SBOM has zero components — schema-valid but empty" >&2
  exit 1
fi

echo "validate-sbom: OK — ${sbom} is schema-valid with ${component_count} components"
