#!/usr/bin/env python3
"""R3: actual paid HTTP reads and durable Outcomes on an ordinary release Worker.

Only localhost workerd, its isolated binding, and the fixture receiver are used.
The cancellation wrapper cancels the real release response bridge; it does not
assert that a TCP client's received bytes equal the server's generated bytes.
"""
import argparse
import copy
import datetime
import hashlib
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import re
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / 'apps/vcs-worker'
FIXTURE = APP / 'tests/launch-read-hooks'
WRANGLER = '4.134.0'
AUDIENCE = 'https://vcs.launch.invalid'
SEED = '5e' * 32
PUBLIC_CASE = 'launch.read_fixture_public'
PRIVATE_CASE = 'launch.read_fixture_private'


def check(condition, message):
    if not condition:
        raise RuntimeError(message)


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def request(origin, path, method='GET', headers=None, body=None):
    req = urllib.request.Request(origin + path, method=method, headers=headers or {}, data=body)
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    try:
        response = opener.open(req, timeout=30)
    except urllib.error.HTTPError as error:
        response = error
    with response:
        return response.status, dict(response.headers), response.read()


def stop(process):
    if process is None:
        return
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait(timeout=10)


class Receiver:
    """Records real hook requests across workerd restarts; never owns server state."""
    def __init__(self):
        self.lock = threading.Lock()
        self.mode = 'allow'
        self.read_serial = 0
        self.lose_outcome = False
        self.calls = []
        self.allowed = {}
        self.outcomes = {}
        self.errors = []

    def snapshot(self):
        with self.lock:
            return copy.deepcopy({'calls': self.calls, 'allowed': self.allowed,
                                  'outcomes': self.outcomes, 'errors': self.errors})

    def handle(self, procedure, body):
        with self.lock:
            self.calls.append({'procedure': procedure, 'body': body})
            if procedure == 'Authorize':
                return {'allow': {}}, False
            if procedure == 'Admit':
                operation = body.get('operation', {})
                read = operation.get('procedure', '').startswith('/mkit.http.v1/')
                if read:
                    if operation.get('audience') != AUDIENCE:
                        self.errors.append('HTTP admission has wrong audience')
                    if body.get('newToRepoBytes') != '0':
                        self.errors.append('HTTP admission omitted explicit zero newToRepoBytes')
                    if operation.get('principal') != {'anonymous': {}}:
                        self.errors.append('HTTP admission manufactured authenticated principal')
                    if operation.get('idempotencyKey') or operation.get('grant') or operation.get('refs'):
                        self.errors.append('HTTP admission manufactured write facts')
                    if body.get('createsNamespace') is not False or body.get('createsRepo') is not False:
                        self.errors.append('HTTP admission manufactured namespace/repository creation')
                    if body.get('packId'):
                        self.errors.append('HTTP admission manufactured a pack id')
                    if self.mode == 'challenge':
                        return {'challenge': {'challenges': [{'scheme': 'Payment', 'value': 'fixture'}],
                                              'description': 'local fixture challenge',
                                              'responseHeaders': [{'name': 'WWW-Authenticate',
                                                                   'value': 'Payment fixture'}]}}, False
                    if self.mode == 'deny':
                        return {'deny': {'code': 'permission_denied', 'message': 'local read denied'}}, False
                    self.read_serial += 1
                    reservation = f'launch-read:{self.read_serial}'
                else:
                    nonce = operation.get('idempotencyKey')
                    reservation = 'launch-write:' + (nonce or str(len(self.calls)))
                self.allowed[reservation] = body
                return {'allow': {'reservationId': reservation,
                                  'responseHeaders': [{'name': 'Payment-Receipt', 'value': reservation}]}}, False
            if procedure == 'Outcome':
                outcome = body.get('outcome', {})
                reservation = outcome.get('reservationId')
                if not isinstance(reservation, str) or reservation not in self.allowed:
                    self.errors.append('Outcome for unknown reservation')
                    return None, False
                operation = self.allowed[reservation]['operation']
                if outcome.get('audience') != operation.get('audience') or \
                        outcome.get('repository') != operation.get('repository'):
                    self.errors.append('Outcome changed admission audience or repository')
                if sum(kind in outcome for kind in ['committed', 'aborted', 'expired', 'readServed']) != 1:
                    self.errors.append('Outcome has no unique terminal kind')
                self.outcomes.setdefault(reservation, []).append(outcome)
                lose = reservation.startswith('launch-read:') and self.lose_outcome
                if lose:
                    self.lose_outcome = False
                return {}, lose
            self.errors.append('Unexpected hook procedure: ' + procedure)
            return None, False


def receiver_server(receiver, port):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *_):
            pass

        def do_POST(self):
            try:
                if self.headers.get('Transfer-Encoding', '').lower() == 'chunked':
                    chunks = []
                    length = 0
                    for _ in range(2048):
                        line = self.rfile.readline(82)
                        check(len(line) <= 80 and line.endswith(b'\r\n'), 'invalid hook chunk header')
                        size = int(line.split(b';', 1)[0], 16)
                        if size == 0:
                            check(self.rfile.readline(82) == b'\r\n', 'unexpected hook trailers')
                            break
                        length += size
                        check(length <= 262144, 'hook body outside fixture cap')
                        piece = self.rfile.read(size)
                        check(len(piece) == size and self.rfile.read(2) == b'\r\n', 'truncated hook chunk')
                        chunks.append(piece)
                    else:
                        raise RuntimeError('too many hook chunks')
                    wire = b''.join(chunks)
                else:
                    length = int(self.headers.get('Content-Length', '0'))
                    check(0 < length <= 262144, 'hook body outside fixture cap')
                    wire = self.rfile.read(length)
                    check(len(wire) == length, 'truncated hook body')
                check(self.headers.get('Content-Type') == 'application/json', 'hook content type')
                check(self.headers.get('Connect-Protocol-Version') == '1', 'hook Connect version')
                check(not any(name.lower().startswith('x-mkit-hook-') for name in self.headers),
                      'isolated binding incorrectly signed')
                body = json.loads(wire)
                check(self.path.startswith('/mkit.server.hooks.v1.HooksService/'), 'unknown hook path')
                result, lose = receiver.handle(self.path.rsplit('/', 1)[-1], body)
                if lose:
                    # The remote side applied the effect but the sender receives
                    # no successful acknowledgement; the durable outbox must retry.
                    self.close_connection = True
                    self.connection.shutdown(socket.SHUT_RDWR)
                    self.connection.close()
                    return
                payload = json.dumps(result).encode()
                self.send_response(200 if result is not None else 404)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Content-Length', str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)
            except (RuntimeError, ValueError, OSError) as error:
                with receiver.lock:
                    receiver.errors.append(type(error).__name__ + ': ' + str(error))
                self.close_connection = True
    return ThreadingHTTPServer(('127.0.0.1', port), Handler)


def await_outcome(receiver, reservation, timeout=40, attempts=1):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        snapshot = receiver.snapshot()
        check(not snapshot['errors'], 'receiver errors: ' + repr(snapshot['errors']))
        seen = snapshot['outcomes'].get(reservation, [])
        if len(seen) >= attempts:
            check(all(item == seen[0] for item in seen), 'one reservation changed terminal Outcome')
            return seen[0]
        time.sleep(0.1)
    raise RuntimeError(f'Outcome {reservation} missing {attempts} delivery attempts')


def admission_count(receiver):
    return sum(call['procedure'] == 'Admit' and
               call['body'].get('operation', {}).get('procedure', '').startswith('/mkit.http.v1/')
               for call in receiver.snapshot()['calls'])


def receipt(headers):
    return next((value for key, value in headers.items() if key.lower() == 'payment-receipt'), None)


def assert_served(receiver, headers, object_id, declared, actual):
    reservation = receipt(headers)
    check(reservation is not None, 'admitted read omitted Payment-Receipt')
    snapshot = receiver.snapshot()
    allowance = snapshot['allowed'].get(reservation)
    check(allowance is not None, 'response reservation not observed at receiver')
    check(int(allowance.get('declaredBytes', '-1')) == declared, 'incorrect priced representation bytes')
    outcome = await_outcome(receiver, reservation)
    served = outcome.get('readServed')
    check(served is not None and int(served.get('bytesServed', '-1')) == actual,
          f'{reservation} expected ReadServed({actual}), got {outcome}')
    import base64
    check(base64.b64decode(served['object']).hex() == object_id, 'Outcome identified wrong object')
    return reservation


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sha', required=True)
    parser.add_argument('--no-build', action='store_true', help='use root-verified HTTP release bundle and runner')
    parser.add_argument('--port', type=int, default=int(os.environ.get('VCS_CONFORMANCE_PORT', '8827')))
    args = parser.parse_args()
    head = git('rev-parse', 'HEAD')
    check(len(args.sha) == 40 and args.sha == head, '--sha must pin current immutable HEAD')
    check(not git('status', '--porcelain', '--untracked-files=normal'), 'commit candidate before evidence')
    check('CARGO_TARGET_DIR' not in os.environ, 'CARGO_TARGET_DIR must remain unset')
    scratch = Path.home() / '.cache/mkit-test-tmp/wp-4-18/launch-read-runtime'
    scratch.mkdir(parents=True, exist_ok=True)
    check(scratch.resolve() == scratch, 'scratch must have no symlink components')
    check(1024 <= args.port <= 65533, 'need three adjacent private ports in 1024..65535')
    for port in range(args.port, args.port + 3):
        with socket.socket() as listener:
            listener.bind(('127.0.0.1', port))
    run = Path(tempfile.mkdtemp(prefix='runtime-', dir=scratch))
    print('R3 evidence directory:', run, flush=True)
    env = dict(os.environ, TMPDIR=str(scratch), CARGO_PROFILE_DEV_DEBUG='0', CARGO_PROFILE_TEST_DEBUG='0',
               WRANGLER_SEND_METRICS='false', WRANGLER_REGISTRY_PATH=str(run / 'registry'))
    runner = ROOT / 'rust/target/debug/mkit-server-conformance'
    evidence = {'candidate_sha': head, 'tree_sha': git('rev-parse', 'HEAD^{tree}'),
                'base_sha': git('rev-parse', 'origin/feat/mkit-server'), 'wrangler': WRANGLER,
                'features': ['http-objects'], 'commands': [], 'checks': [], 'result': 'RUNNING',
                'limitations': ['Controlled bridge cancellation is distinct from TCP disconnect',
                                'No internal operation counters or arbitrary storage-failure injection',
                                'Reconcile timeout race remains separate from completed read retry/restart']}
    receiver = Receiver()
    server = None
    process = None
    transient = run / 'token-fixture.json'

    def invoke(command, log, cwd=ROOT / 'rust', extra_env=None):
        evidence['commands'].append({'argv': command, 'log': str(log.relative_to(run))})
        with log.open('w') as output:
            completed = subprocess.run(command, cwd=cwd, env=extra_env or env, stdout=output,
                                       stderr=subprocess.STDOUT, timeout=900)
        check(completed.returncode == 0, 'command failed; see ' + str(log))

    try:
        if not args.no_build:
            invoke(['cargo', 'build', '--locked', '-p', 'mkit-server-conformance', '--bin',
                    'mkit-server-conformance'], run / 'runner-build.log')
            invoke(['worker-build', '--release', '--features', 'http-objects'],
                   run / 'worker-build.log', APP)
        check(runner.is_file(), 'build the conformance runner first')
        evidence['runner_sha256'] = digest(runner)
        artifact = run / 'artifact'
        shutil.copytree(APP / 'build', artifact)
        for name in ['index_bg.wasm', 'index.js', 'worker/shim.mjs']:
            check((artifact / name).is_file(), 'missing release artifact: ' + name)
        check((artifact / 'index_bg.wasm').read_bytes().startswith(b'\0asm'), 'invalid wasm artifact')
        evidence['artifact_sha256'] = {str(path.relative_to(artifact)): digest(path)
                                       for path in artifact.rglob('*') if path.is_file()}
        wrapper = run / 'wrapper.mjs'
        wrapper.write_text((FIXTURE / 'wrapper.mjs').read_text().replace('__RELEASE_MODULE__',
                                                                        str(artifact / 'index.js')))
        origin = f'http://127.0.0.1:{args.port}'
        classes = [('REFSTORE', 'RefStore'), ('NS_COORD', 'NsCoordinator'), ('REF_SHARD', 'RefShard'),
                   ('REPO_INDEX', 'RepoIndexShard'), ('CONTENT_INDEX', 'ContentIndexShard')]
        config = {'name': 'mkit-launch-read-runtime', 'main': str(wrapper),
                  'compatibility_date': '2026-09-09', 'build': {'command': 'true'},
                  'vars': {'AUTH_AUDIENCE': AUDIENCE, 'LAUNCH_PROFILE': 'uno', 'WORKERS_PLAN': 'paid',
                           'INDEXED_MODE': 'true', 'ADDRESSING': 'multi', 'SHARDING': 'd34',
                           'NAMESPACE_POLICY': 'any', 'UNSAFE_OPEN_NAMESPACES': 'true',
                           'RETENTION': 'permanent', 'STORAGE_LEASES': 'false', 'GC_ENABLED': 'false',
                           'TICKET_KEYS': 'launch-ticket ' + '11' * 32, 'HTTP_OBJECTS': 'true',
                           'URL_TOKEN_KEYS': 'active ' + '22' * 32, 'HTTP_ADMIT_READS': 'true',
                           'HOOK_ROLES': 'authorize,admit,outcome', 'HOOK_TIMEOUT_MS': '5000'},
                  'r2_buckets': [{'binding': 'STORAGE', 'bucket_name': 'read-objects'},
                                 {'binding': 'BACKUPS', 'bucket_name': 'read-backups'}],
                  'durable_objects': {'bindings': [{'name': name, 'class_name': cls} for name, cls in classes]},
                  'migrations': [{'tag': 'v1', 'new_sqlite_classes': [cls for _, cls in classes]}],
                  'services': [{'binding': 'ADMISSION_HOOK', 'service': 'mkit-launch-read-hooks'}]}
        hooks = json.loads((FIXTURE / 'wrangler.json').read_text())
        hooks.update({'main': str(FIXTURE / 'worker.mjs'), 'dev': {'port': args.port + 1},
                      'vars': {'RECEIVER_ORIGIN': f'http://127.0.0.1:{args.port + 2}'}})
        for name, data in [('worker.json', config), ('hooks.json', hooks)]:
            (run / name).write_text(json.dumps(data, indent=2) + '\n')
        server = receiver_server(receiver, args.port + 2)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        command = ['npx', '--yes', 'wrangler@' + WRANGLER, 'dev', '--local',
                   '--config', str(run / 'worker.json'), '--config', str(run / 'hooks.json'),
                   '--ip', '127.0.0.1', '--port', str(args.port), '--persist-to', str(run / 'state'),
                   '--show-interactive-dev-session=false']

        def start(name):
            nonlocal process
            output = (run / name).open('w')
            try:
                child = subprocess.Popen(command, cwd=APP, env=env, stdout=output,
                                         stderr=subprocess.STDOUT, start_new_session=True)
            finally:
                output.close()
            process = child
            evidence['commands'].append({'argv': command, 'log': name})
            deadline = time.monotonic() + 120
            while time.monotonic() < deadline:
                check(child.poll() is None, 'wrangler exited; see ' + name)
                try:
                    status, _, body = request(origin, '/mkit.transport.v1.TransportService/GetServerInfo',
                                              'POST', {'content-type': 'application/json',
                                                       'connect-protocol-version': '1'}, b'{}')
                    if status == 200:
                        info = json.loads(body)
                        check(info.get('indexedMode') is True, 'indexed launch capability absent')
                        return child
                except (urllib.error.URLError, TimeoutError, ConnectionError):
                    pass
                time.sleep(0.25)
            stop(child)
            raise RuntimeError('local workerd readiness timed out')

        process = start('wrangler.log')
        status, _, _ = request(origin, '/__mkit_test/stats')
        check(status != 200, 'release artifact exposes test-faults route')
        common = [str(runner), 'wire', '--base-url', origin, '--auth', 'auth-v2', '--audience', AUDIENCE,
                  '--repository', 'default', '--signer-seed-hex', SEED, '--run-id', 'launch-read-runtime',
                  '--atomic-advance', '--fresh-target', '--milestone', 'M4', '--sharding', 'd34',
                  '--features', 'indexed-async,indexed-mode,multi-repo,tickets,auth-v2,http-objects,timers,launch-read-fixture']

        def fixture_case(case):
            transient.unlink(missing_ok=True)
            invoke([*common, '--filter', case], run / (case + '.tap'),
                   extra_env=dict(env, MKIT_LAUNCH_READ_FIXTURE=str(transient)))
            tap = (run / (case + '.tap')).read_text()
            check('# SKIP' not in tap and re.search(r'^ok 1 - ' + re.escape(case) + r'(?:\s|$)', tap, re.M),
                  'required read fixture case skipped or failed')
            check(transient.is_file(), 'fixture case omitted token file')
            data = json.loads(transient.read_text())
            transient.unlink()
            return data

        public = fixture_case(PUBLIC_CASE)
        raw = f"/{public['repository']}/-/objects/{public['object']}"
        token = raw + '?token=' + urllib.parse.quote(public['token'], safe='')
        data = bytes(((i * 17) ^ (i >> 9)) & 255 for i in range(public['bytes']))
        for name, path, method, headers, wanted_status, wanted in [
            ('public_raw_full', raw, 'GET', {}, 200, data),
            ('public_token_full', token, 'GET', {}, 200, data),
            ('public_raw_range', raw, 'GET', {'Range': 'bytes=19-65554'}, 206, data[19:65555]),
            ('public_head_zero', raw, 'HEAD', {}, 200, b'')]:
            status, response_headers, body = request(origin, path, method, headers)
            check(status == wanted_status and body == wanted, name + ' status or bytes differ')
            declared = len(wanted) if method != 'HEAD' else len(data)
            assert_served(receiver, response_headers, public['object'], declared, len(wanted))
            check(any(key.lower() == 'cache-control' and value.startswith('private,')
                      for key, value in response_headers.items()), name + ' paid response cache policy')
            evidence['checks'].append({'name': name, 'result': 'PASS', 'bytes': len(wanted)})
        etag = '"' + public['object'] + '"'
        before = admission_count(receiver)
        status, _, _ = request(origin, raw, headers={'If-None-Match': etag})
        check(status == 304, 'validator expected 304')
        status, _, _ = request(origin, raw, headers={'Range': f"bytes={len(data)}-"})
        check(status == 416, 'unsatisfiable range expected 416')
        check(admission_count(receiver) == before, '304/416 reached remote admission')
        evidence['checks'].append({'name': '304_416_before_admission', 'result': 'PASS'})
        for mode, expected in [('challenge', 402), ('deny', 403)]:
            with receiver.lock:
                receiver.mode = mode
            allowed_before = len(receiver.snapshot()['allowed'])
            for method in ['GET', 'HEAD']:
                status, response_headers, body = request(origin, raw, method)
                check(status == expected, f'{mode} {method}: HTTP {status}')
                check(body != data and (method != 'HEAD' or not body), mode + ' emitted payload bytes')
                check(receipt(response_headers) is None, mode + ' falsely emitted allow receipt')
            check(len(receiver.snapshot()['allowed']) == allowed_before, mode + ' allocated allowance')
            evidence['checks'].append({'name': mode + '_get_head', 'result': 'PASS'})
        with receiver.lock:
            receiver.mode = 'allow'
        # Cancel the real release response bridge without altering the body or
        # counting an outer JS/client buffer as generated server bytes.
        for mode in ['before', 'after']:
            prior = receiver.snapshot()['allowed']
            status, _, body = request(origin, raw, headers={'x-launch-read-cancel': mode})
            check(status == 200, 'bridge cancellation request failed')
            canceled = json.loads(body)
            new = set(receiver.snapshot()['allowed']) - set(prior)
            check(len(new) == 1, 'bridge cancellation did not create exactly one reservation')
            reservation = new.pop()
            outcome = await_outcome(receiver, reservation)
            if mode == 'before':
                check(canceled['generated'] == 0 and
                      outcome.get('aborted', {}).get('reason') == 'ABORT_REASON_INTERNAL',
                      'cancel before first poll did not settle Aborted')
            else:
                generated = canceled['generated']
                check(0 < generated < len(data), 'after-first-chunk fixture did not exercise a partial body')
                check(int(outcome.get('readServed', {}).get('bytesServed', '-1')) == generated,
                      'partial cancellation Outcome differs from actual polled bridge bytes')
            evidence['checks'].append({'name': 'bridge_cancel_' + mode, 'result': 'PASS',
                                       'bytes': canceled['generated']})
        # Lose the remote acknowledgement after its effect. Restart workerd with
        # the same durable store before the retry; the receiver remains alive.
        with receiver.lock:
            receiver.lose_outcome = True
        status, response_headers, body = request(origin, raw)
        check(status == 200 and body == data, 'lost-reply read failed')
        reservation = receipt(response_headers)
        check(reservation is not None, 'lost-reply read omitted reservation')
        await_outcome(receiver, reservation)
        stop(process)
        process = None
        process = start('wrangler-restart.log')
        outcome = await_outcome(receiver, reservation, timeout=60, attempts=2)
        check(int(outcome.get('readServed', {}).get('bytesServed', '-1')) == len(data),
              'restart lost or changed completed read settlement')
        evidence['checks'].append({'name': 'lost_outcome_reply_restart_same_terminal', 'result': 'PASS'})
        private = fixture_case(PRIVATE_CASE)
        check(private['repository'] == public['repository'] and private['object'] == public['object'],
              'private phase changed the published fixture')
        before = admission_count(receiver)
        status, _, _ = request(origin, raw)
        check(status == 404 and admission_count(receiver) == before, 'unauthorized private read reached admission')
        private_path = raw + '?token=' + urllib.parse.quote(private['token'], safe='')
        for name, method, headers, wanted in [
            ('private_token_full', 'GET', {}, data),
            ('private_token_head', 'HEAD', {}, b''),
            ('private_token_range', 'GET', {'Range': 'bytes=3-1026'}, data[3:1027])]:
            status, response_headers, body = request(origin, private_path, method, headers)
            check(status == (206 if headers else 200) and body == wanted, name + ' response differs')
            assert_served(receiver, response_headers, private['object'],
                          len(data) if method == 'HEAD' else len(wanted), len(wanted))
            evidence['checks'].append({'name': name, 'result': 'PASS', 'bytes': len(wanted)})
        check(not receiver.snapshot()['errors'], 'receiver recorded invalid protocol behavior')
        check(git('rev-parse', 'HEAD') == head and not git('status', '--porcelain', '--untracked-files=normal'),
              'candidate changed during run; evidence invalidated')
        evidence['result'] = 'PASS'
    except Exception as error:
        evidence['result'] = 'FAIL'
        evidence['error'] = str(error)
        raise
    finally:
        transient.unlink(missing_ok=True)
        stop(process)
        if server is not None:
            server.shutdown()
            server.server_close()
        (run / 'receiver-calls.json').write_text(json.dumps(receiver.snapshot(), indent=2) + '\n')
        evidence['finished_utc'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
        evidence['log_sha256'] = {str(path.relative_to(run)): digest(path) for path in run.rglob('*')
                                  if path.is_file() and path.suffix in {'.log', '.tap', '.json'}
                                  and path.name != 'evidence.json'}
        (run / 'evidence.json').write_text(json.dumps(evidence, indent=2) + '\n')
        print('R3 evidence:', run / 'evidence.json', flush=True)
    print('PASS release paid-read binding component; complete matrix remains independently gated')


if __name__ == '__main__':
    try:
        main()
    except (RuntimeError, OSError, subprocess.SubprocessError, ValueError) as error:
        print('R3 release probe failed:', error, file=sys.stderr)
        sys.exit(1)
