"""Explicitly gated writer for SPEC-SERVER-ACCESS committed JSON vectors.

Normal tests only read the files. Run with MKIT_WRITE_GOLDEN=1 when
intentionally changing the wire contract, then review every generated byte.
"""
import os
from pathlib import Path

import blake3

ROOT = Path(__file__).resolve().parents[3] / "rust/tests/golden/server-access"

BODIES = {
    "get.json": b'{"version":1}\n',
    "initialize.json": b'{"version":1,"collaborators":[]}\n',
    "invalid-duplicate.json": b'{"version":1,"version":1}\n',
    "replace.json": b'{"version":1,"expected_generation":"1","collaborators":[]}\n',
}

META = {
    "get.meta.json": b'{"method":"POST","path":"/mkit/host/v1/GetPolicy","status":200,"generation":"1","response":"initialize-response.json"}\n',
    "initialize.meta.json": b'{"method":"POST","path":"/mkit/host/v1/InitializePolicy","status":200,"generation":"1","response":"initialize-response.json"}\n',
    "invalid-duplicate.meta.json": b'{"method":"POST","path":"/mkit/host/v1/GetPolicy","status":400,"code":"invalid_argument","response":"invalid-response.json"}\n',
    "replace.meta.json": b'{"method":"POST","path":"/mkit/host/v1/ReplacePolicy","status":200,"generation":"2","response":"replace-response.json"}\n',
}

OWNER = b"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c"
RESPONSES = {
    "conflict-response.json": b'{"code":"conflict"}\n',
    "initialize-response.json": b'{"version":1,"audience":"http://localhost:8791","repository":"managed-test","owner":"' + OWNER + b'","generation":"1","collaborators":[]}\n',
    "invalid-response.json": b'{"code":"invalid_argument"}\n',
    "replace-response.json": b'{"version":1,"audience":"http://localhost:8791","repository":"managed-test","owner":"' + OWNER + b'","generation":"2","collaborators":[]}\n',
    "unavailable-response.json": b'{"code":"unavailable"}\n',
}


def main():
    if os.environ.get("MKIT_WRITE_GOLDEN") != "1":
        raise SystemExit("set MKIT_WRITE_GOLDEN=1 to rewrite committed vectors")
    ROOT.mkdir(parents=True, exist_ok=True)
    for name, body in {**BODIES, **META, **RESPONSES}.items():
        (ROOT / name).write_bytes(body)
    manifest = "# Fixed management JSON request/response bytes. Hashes are BLAKE3 over exact file bytes,\n# including the final newline. Update only via reviewed fixture changes.\n"
    for name, body in sorted({**BODIES, **RESPONSES}.items()):
        manifest += f"{blake3.blake3(body).hexdigest()}  {name}\n"
    (ROOT / "MANIFEST.txt").write_text(manifest)


if __name__ == "__main__":
    main()
