// Ambient augmentation for the `CONTROL_TOKEN` Worker *secret*.
//
// `worker-configuration.d.ts` is generated by `wrangler types` (the
// `cf-typegen` package script) purely from `wrangler.jsonc`'s `vars` +
// bindings — it has no way to know about secrets set out-of-band via
// `wrangler secret put` (deploy) / `.dev.vars` (local `wrangler dev`), so
// `CONTROL_TOKEN` never appears there. This file merges an additional
// `CONTROL_TOKEN` field onto the SAME global `Env` interface
// `worker-configuration.d.ts` declares (plain global declaration merging —
// no import/export here, so this stays a script, not a module).
//
// Typed `string | undefined`, not `string`: an unset secret is an expected,
// must-handle state — `spammer.ts`'s `/control` auth check fails EVERY
// request closed when `CONTROL_TOKEN` is undefined (see wrangler.jsonc's own
// comment), never falls open just because the secret hasn't been configured
// yet in a given environment.
interface Env {
  CONTROL_TOKEN?: string;
  /**
   * Opt-in gate for the automatic per-tick Workers AI content refresh
   * (`spammer.ts`'s `alarm()`) — must be exactly "true" to fire; unset (the
   * default, deliberately not declared in wrangler.jsonc's `vars`) means the
   * refresh never runs on its own. A manual refresh is still always
   * available via `/control?action=refresh-content`. See spammer.ts's
   * `alarm()` doc comment for why this defaults off.
   */
  AI_CONTENT_AUTO_REFRESH?: string;
  /**
   * Opt-in gate for per-event AI-personalized replies (#853's ledger,
   * #854's `emitOne` wiring) — must be exactly "true" to ever call
   * `generatePersonalizedReply`; unset (the default, deliberately not
   * declared in wrangler.jsonc's `vars`) means every response chat reply
   * uses `responder.ts`'s `chooseReplyText` template fallback only, with the
   * personalization budget ledger never spent. Mirrors
   * `AI_CONTENT_AUTO_REFRESH`'s opt-in posture and #855's rollout plan
   * (templates only until the pipeline is proven, THEN grant budget).
   */
  AI_REPLY_PERSONALIZATION?: string;
  /**
   * Comma-separated allowlist of additional pubkeys (hex) `responder.ts`'s
   * `mergedSyntheticPubkeys` treats as non-human on top of the 64 synthetic
   * pool identities — e.g. legacy seeded demo authors, if any exist (#848:
   * "a small config allowlist of additional 'known non-human' pubkeys ...
   * empty by default"). Unset/empty means the pool alone is the synthetic
   * set. Trimmed and lowercased entry-by-entry, not case- or
   * whitespace-sensitive.
   */
  RESPONDER_NONHUMAN_ALLOWLIST?: string;
}
