// Ambient augmentation for the `CONTROL_TOKEN` Worker *secret*.
//
// `worker-configuration.d.ts` is generated by `wrangler types` (the
// `cf-typegen` package script) purely from `wrangler.jsonc`'s `vars` +
// bindings — it has no way to know about secrets set out-of-band via
// `wrangler secret put` (deploy) / `.dev.vars` (local `wrangler dev`), so
// `CONTROL_TOKEN` never appears there. This file merges an additional
// `CONTROL_TOKEN` field onto the SAME global `Env` interface
// `worker-configuration.d.ts` declares (plain global declaration merging —
// no import/export here, so this stays a script, not a module).
//
// Typed `string | undefined`, not `string`: an unset secret is an expected,
// must-handle state — `spammer.ts`'s `/control` auth check fails EVERY
// request closed when `CONTROL_TOKEN` is undefined (see wrangler.jsonc's own
// comment), never falls open just because the secret hasn't been configured
// yet in a given environment.
interface Env {
  CONTROL_TOKEN?: string;
  /**
   * Opt-in gate for the automatic per-tick Workers AI content refresh
   * (`spammer.ts`'s `alarm()`) — must be exactly "true" to fire; unset (the
   * default, deliberately not declared in wrangler.jsonc's `vars`) means the
   * refresh never runs on its own. A manual refresh is still always
   * available via `/control?action=refresh-content`. See spammer.ts's
   * `alarm()` doc comment for why this defaults off.
   */
  AI_CONTENT_AUTO_REFRESH?: string;
}
